### ISSUE TITLE
dialog: can't use enter to move through continue windows

### ISSUE THREAD

**Issue by lynxlynxlynx** [bradallred/gemrb#100]
focus issue, I guess.

**Comment by bradallred** [comment]
well, sort of. The portrait/option windows must go on top because the button window is actually much wider than it needs to be (presumably the same window is used for multiple resolutions). So yeah, the result is that we have focus on the "wrong" window.

That commit should work around it, but might also introduce some crashing until hot key deregistration is added (which was an issue before anyway)

the overlapping windows is waht is behind issue #102 as well
