### ISSUE TITLE
script listing causes an assert

### ISSUE THREAD

**Issue by lynxlynxlynx** [bradallred/gemrb#27]
(we disable bugs on the other repo)
running bg2 and going into guirec customisation, choosing the (ai) scripts button reliably asserts:
`gemrb/core/GUI/TextSystem/TextContainer.cpp:476: void GemRB::ContentContainer::LayoutContentsFrom(std::__cxx11::list<GemRB::Content*>::const_iterator): Assertion `!layoutFrame.Dimensions().IsEmpty()' failed.  `

the stack is always destroyed for me, so I didn't investigate further. Seems like the latest code changes caused several new problems, so I'll check that first (~~game loaded with wrong area~~, button overlay insets misaligned and only work for the first portrait, copyresref change broke travis). Perhaps related, the sound listing in cg also shows empty.

**Comment by bradallred** [comment]
i'll look into these later on today. thank you.

**Comment by bradallred** [comment]
I've fixed the assert. the lists are still "empty"; havn't attempted to figure out why.

all the other issues should be resolved.

**Comment by lynxlynxlynx** [comment]
Can confirm. Closing gemrb right after the empty script window shows a resource mgmt bug though — a palette isn't released, so the exit isn't clean.

I was researching why the map window is not working and found the problem. During the refactoring of CreateControl calls last year, inheriting of the reused control's size (frame/region) was removed. All the map creation is explicitly called with an empty region, so the control creation fails. The control's window is not available in the binding though, so that will have to change.

**Comment by bradallred** [comment]
drat. opening the character record window at all (then quitting) will trigger that.

I immediately suspect the markup parser at fault since the other windows don't trigger this and i cant think of anything else on that window that would mess with palettes.

IIRC the map control has a bunch more wrong with it than that... I've been ignoring that. I think I have a stash from last year that got it halfway working again. It is also the "states2" font destruction the crash occurs in lending further credence to the markup parser being at fault.

**Comment by bradallred** [comment]
-Palette issue is fixed now- doesn't crash anymore, but its not fixed. We should open new issues for the resource lists and map thing and close this.

**Comment by lynxlynxlynx** [comment]
the map has other issues for the spell effects and the worldmap not being ported (plus perhaps the markers), but this region thing is as simple as described. Settting w&h in gdb was enough to get it drawn.
