### ISSUE TITLE
Tooltip incorrectly rendered when multiline or > 128px wide

### ISSUE THREAD

**Issue by bradallred** [bradallred/gemrb#3]
Currently tooltips background drawing is implemented like the originals. That is the positioning of the background is controlled by the `XPos` and `YPos` of the sprites. The result is that multiline tooltips having their text too low.

Also, the cursor buffer is only 128px wide which is too small to fit a fully extended tooltip (the main bg sprite alone is 128px wide). simply extending the buffer is not quite enough to fix it, however, because the `XPos` setting on the sprite is only `64px`.

It would probably be easier to ignore `XPos` and `YPos` on those sprites and programmatically center things.

**Comment by lynxlynxlynx** [comment]
Even some shorter ones get clipped. An example is the Talk icon in the action window. Could be related to F1 prepending not being accounted for.

**Comment by bradallred** [comment]
I'm actually not seeing a problem with that tooltip:
![image](https://user-images.githubusercontent.com/1126744/27494413-ffb62448-580a-11e7-90cb-e508b38301c1.png)

**Comment by lynxlynxlynx** [comment]
Here most look like "|- bla", where the pipe char is too thin, like something got clipped or with a centered dot instead. Something for another time.

your ss also shows we likely have a 1-2px error in constructing the bg (left side).

**Comment by bradallred** [comment]
yeah, the bg image just needs to be clipped to half the width of the edges

**Comment by bradallred** [comment]
let me know if these look good to you now. might need a separate issue for the hotkey bit.

**Comment by bradallred** [comment]
also, I don't know where that pipe is coming from. assuming the hotkey is set to F1 that should be handled in `Button::TooltipText()` may want to check the actual text returned there.

**Comment by lynxlynxlynx** [comment]
Most work fine. Return to game gets clipped as per #8, the odd artifacts remain for the action row and if you select multiple characters and look at the formation buttons, they are without the ending parts of the scrolls. They're drawn while the animation is running, but then mostly vanish. Sane for ring of protection +1, metaspell influence amulet, mail of the dead +2 ...

quickslot oil of speed gets bumped to multiline for no obvious reason, but it also turns out that anything in that quickslot does, even the empty quickslot tooltip. Same happens here with twohanded sword +3 in a weapon slot.

So at minimum the max size should be increased.

**Comment by bradallred** [comment]
tested with a couple dozen items. seems fixed.

**Comment by lynxlynxlynx** [comment]
yeah, everything but the artifacts+quickitemslot is fine. Unless you're nitpicky, then we should start wrapping a px or two earlier (eg. amulet of the seldarine).

**Comment by bradallred** [comment]
the margins are probably arbitrary. try shrinking it by 1.
