### ISSUE TITLE
travis build broken

### ISSUE THREAD

**Issue by lynxlynxlynx** [bradallred/gemrb#37]
Got a suspect now though. Previously the minimal test didn't do any gui stuff, now it does pop open a window for a tick or two. That could easily cause the crash, since travis workers have no screens. My terminals have some sort of framebuffer going on, so I can't verify it there. It does exit with 0.

**Comment by bradallred** [comment]
cool. thanks for looking into this.

**Comment by bradallred** [comment]
I got backtrace output working in travis (sometimes?)

more importantly the crash is resolved, but it is still failing because the directories are apparently wrong: https://travis-ci.org/gemrb/gemrb/jobs/395312391

I don't remember changing anything in the Travis or cfg that would make it be looking in a different location. @lynxlynxlynx  Do you see anything obviously wrong?

**Comment by lynxlynxlynx** [comment]
Quite amazing that it ran that far with all the checks we have for essentials. I think something is fucky on the travis side, eg. these two errors disagree:

> [DirectoryIterator/WARNING]: Cannot readdir: ./gemrb
> [PluginLoader/DEBUG]: Error: ./gemrb/plugins/: cannot read file data: Is a directory

**Comment by lynxlynxlynx** [comment]
Actually I can reproduce this on my own machine. Looking into it ...

**Comment by lynxlynxlynx** [comment]
First, it doesn't actually cause any failure — the tests run fine. The last travis error is a build one, but only for gcc:
https://travis-ci.org/gemrb/gemrb/jobs/395312392#L1258
I'll just remove the declaration, since it has no external users and lack of will.

I suspect the new logging code exposes a bit that doesn't like relative paths and that's all, practically noise.

**Comment by lynxlynxlynx** [comment]
And it's passing, closing.

**Comment by bradallred** [comment]
awesome, thanks
