### ISSUE TITLE
Nested modal windows?

### ISSUE THREAD

**Issue by bradallred** [bradallred/gemrb#44]
I have an unfinished stash from last year that seems to add support for nested modal windows... I'm presuming this must be needed somewhere, but I have no recollection of where.

**Comment by lynxlynxlynx** [comment]
My guess would be guirec, as the customisation windows go pretty deep. Yeah and they're of different shapes and sizes.

**Comment by lynxlynxlynx** [comment]
guirec doesn't need it, one level is enough.

**Comment by lynxlynxlynx** [comment]
Ok, I partially retract that. Due to the missing window frames, it's hard to say, but there is some ugly background swapping going on in guirec. If all the modality was turned to black, it probably wouldn't matter.

**Comment by lynxlynxlynx** [comment]
In bg2 I could only found the HLA levelup window to be narrower than its parent, so that shows below. From what I remember MODAL_SHADOW_GRAY just doesn't work any more on sdl1?

In bg1, you can see 4 windows at once by customizing colors through GUIREC, but it's the same only graphical issue. I don't see any artifacts, perhaps the previous comment was from sdl2.

**Comment by bradallred** [comment]
there is no reason `MODAL_SHADOW_GRAY` shouldn't work, so if it doesn't let's open an issue for it.

If we don't want to draw windows below modals we can address that pretty easily too I think.

**Comment by lynxlynxlynx** [comment]
It's just not dithering, so it's like a blank modal.

**Comment by lynxlynxlynx** [comment]
I'm closing this — didn't see any need for changes while testing all the guis. The bg1 color case works fine now too.
