### ISSUE TITLE
loading game from ingame crashes

### ISSUE THREAD

**Issue by lynxlynxlynx** [bradallred/gemrb#61]
in invalidating actionTimer during mouse handling. Looks like a memory corruption, so the cause is earlier.

**Comment by bradallred** [comment]
seems to be a dangling reference to the load button/window.

from first glance it appears to be the following chain of events:

1. load button is clicked
2. this first closes the window it is located in then attempts to open the new window
3. this causes `WindowManager::MakeWindow` to run which deletes the closed windows
4. the mouse up event gets delivered to a deleted window/button

**Comment by bradallred** [comment]
I looked deeper and I was close, but not quite:

1. load button mouse up handler runs and closes its own window (not a problem, window is not deleted)
2. the handler also opens the next window eventually invoking `WindowManager::MakeWindow` deleting the closed window (now we have a problem)
3. the window destructor deletes the button (you can see a nice log message: "Destroying control inside event handler, crash may occur!")
4. the button handler returns only now `this` has been deleted. crash occurs here (for me since im running with asan).

not sure what we are doing differently here. clearly we have other cases of a button both closing its window while opening another. probably we do it in the other order: first open the new window, then close the old window.

Not sure we want to rely on that, but for now its the easiest fix :)

Seems like the only 100% safe thing to do would be to add a method to `Window` to scan its controls to see if they are in a handler. then we avoid deleting windows if they are in a handler (they will get cleaned up the next time a window is opened).

**Comment by lynxlynxlynx** [comment]
Yeah, the warnings were there in master too, just don't remember if from here.

**Comment by bradallred** [comment]
8a2afce seems to have fixed this

tho there is an issue with the options window being open when the new game is loaded. obviously closing that window from the button handler would serve, but the appropriate thing to do is the FIXME from 24f436c
