### ISSUE TITLE
can't make guiload scrollbar mousescroll scrollable

### ISSUE THREAD

**Issue by lynxlynxlynx** [bradallred/gemrb#78]
It doesn't work by default and marking it with SetDefaultScrollBar is even worse — immobilizes it completely.

**Comment by lynxlynxlynx** [comment]
same thing is visible already in the save window, which already makes it the default.

**Comment by bradallred** [comment]
I don't have a mouse to work on this currently (SDL 1.2 has never accepted the trackpad scrolling). `SetDefaultScrollBar()` is dead code; focusing the control is the way to go now.

**Comment by bradallred** [comment]
should scroll if your mouse is over it now. gonna have to make the mousewheel events return a bool like the keyboard events do to make it work while hovering other views.

**Comment by lynxlynxlynx** [comment]
Isn't the commit counterproductive then? One click and focus is lost. One of the ideas of this branch was to enable more intuitive scrolling in windows with more than one scrollbar and things like the profs/skills window are probably the worst (3x scrollbar, two of them non-ta).

**Comment by bradallred** [comment]
yes, the idea is to deliver the event to the view directly below the cursor and bubble up until the event is handled. I'll have to find a mouse to actually delve into this.

its true this probably needs to be rethought a bit due to the nature of the original interface. the ultimate problem is we are dealing with "scrolling" that isn't actually scrolling anything so mouse wheel events to the other views bubble up to the window (which doesn't actually have anything to scroll) and not the scrollbar. if this were actually scrolling something it would work just fine 😛

**Comment by lynxlynxlynx** [comment]
well yeah, hence the SetDefaultScrollBar for us to decide case-by-case where it should end up if nothing caught it.

**Comment by bradallred** [comment]
can't we just use the action callback system to tap into the scrollevent and forward it to the scrollbars?

**Comment by lynxlynxlynx** [comment]
I don't know, how would it know which scrollbar to pick? Scrolling all sounds like a bad idea.

I think the most intuitive (to the user) non-hover behaviour would be to scroll the closest view associated with an active scrollbar or the scrollbar itself.

**Comment by bradallred** [comment]
I was thinking there was a way to attach event handlers to a view to listen for mouse events (e.g. `window.SetEvent (ON_SCROLL, ScrollBarUpdated)`) and have the handler just relay those to the scroll bar, but that functionality exists at the `Control` level and I don't feel like moving it right now and only click is currently implemented as documented by issue #31 . the old method will have to do I suppose.
