### ISSUE TITLE
scrolling on msgwin resizing

### ISSUE THREAD

**Issue by lynxlynxlynx** [bradallred/gemrb#89]
when resizing to a bigger view, the content is not scrolled. Eg. going from two lines to the bigger windows still just shows only two lines — until new input is added. Works fine the other way around

pause/unpause in succession to generate the text.

**Comment by lynxlynxlynx** [comment]
Maybe the same issue (follow up on #86):
when resizing to a smaller window, there is a pixel or two height error until new content is added, as if the view isn't centered properly. You can see it as an artifact at the bottom, showing the next line. So again scrolling.

**Comment by bradallred** [comment]
the not scrolling is actually intentional! Its horribly annoying (to me at least) when you change the size of the window and have to rescroll to the position you were at before you resized. If you have enough text to fill the large one you probably wouldn't have noticed 😛 This was actually one of my biggest pet peeves with the original and something I was happy to finally "fix" :)

certainly the scrollbar ought to be visible and functional in the cases where there isn't enough text, or simply scroll to the bottom in that case, both options work for me (but i really like keeping the scroll position the same otherwise).

**Comment by lynxlynxlynx** [comment]
There is enough text to fit the bigger windows, but it out of _view_.

I think you meant the position resetting if your in the middle of a scroll, about which I agree — the scroll position/text should be maintained. But this bug isn't about that.

**Comment by bradallred** [comment]
yes, thats what i meant :)

I only mentioned it as an aside; I agree something should be done about this. Scroll it to the bottom in this case? thats certainly the easiest fix and matches the current behavior.

**Comment by lynxlynxlynx** [comment]
After a good night's sleep, I can't distinguish the two bugs any more. You resize the msgwin to see more of the text, so if it moves under you, it's bad ux. The relative content position should always be maintained, which means rescrolling, but invisible to the user, I guess (except for the trough position).

It's literally like reading an actual scroll and just unwinding at one end.

**Comment by bradallred** [comment]
its more tricky, but I agree it would be better UX to "lock" it to the bottom (of the text visible at the time you toggle) rather than the top.

**Comment by bradallred** [comment]
Is this more like what you expect?

**Comment by lynxlynxlynx** [comment]
Yep. The only case when it behaves unexpectedly is if you're scrolled to the bottom and then resize the window back up. You'll end up moved in the middle of the content.

**Comment by bradallred** [comment]
I think we are happy with this now
